sudo: required
servies:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_003b3e01c5f5_key -iv $encrypted_003b3e01c5f5_iv -in multi-docker.json.enc -out multi-docker.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-could-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - docker build -t sherondale/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sherondale/react-test npm test -- --coverage

after_success:
  - docker build -t sherondale/multi-docker-client ./client
  - docker build -t sherondale/multi-docker-nginx ./nginx
  - docker build -t sherondale/multi-docker-server ./server
  - docker build -t sherondale/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sherondale/multi-docker-client
  - docker push sherondale/multi-docker-nginx
  - docker push sherondale/multi-docker-server
  - docker push sherondale/multi-docker-worker
