apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: <TLS_NAME>
spec:
  secretName: <SECRET_NAME>
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: <SECRET_NAME>
  dnsNames:
    - <DNS_NAME>
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - <DNS_NAME>
